### PR TITLE
Implementation of latest specifications

### PR DESCRIPTION
**Pull request by muellersSAW**
This pull request contains the changes in grammar and parser classes to fit the new specifications as it is described in https://www.loc.gov/standards/datetime/ (Differences). The L2 feature "Significant digits" i still not implemented

### CODE REVIEW

**Comment by fatzh** [comment]
this would be great to merge, thanks!

**Comment by krzysztofjeziorny** [comment]
@muellersSAW Is your version compatible with Django 4.2 and Python 3.11?

**Comment by krzysztofjeziorny** [comment]
@muellersSAW Could you enable issues on your fork? I'd like to ask a question.

**Comment by aweakley** [comment]
Thanks very much for this work @muellersSAW. I'm merging it into a new v5 branch in this repo in two stages, and then reverting the name change. Sorry I missed it last year.

**Comment by rettinghaus** [comment]
@aweakley As v5 branch is merged, this one can be closed now.

**Comment by aweakley** [comment]
Thank you

**Pull request closed without merging**
